# Site settings
title: Haoyu Dong MSc. 
email: h.dong@tue.nl
description: Academic webpage of Haoyu Dong
baseurl: ""
url: ""
affiliation: Eindhoven University of Technology

# Google analytics ID
google_analytics: 

# Location info. (shown in footer)
location: >
  Coordinates: <br/>
  Future Everyday Group <br/>
  Eindhoven University of Technology <br/>
  5612AZ, Eindhoven<br/>
  the Netherlands<br/>

# Contact info. (shown in footer)
contact: >
    Contact Haoyu via email: <a href="mailto:h.dong@tue.nl" target="_blank">h.dong@tue.nl</a> <br/>

# Pages shown in navbar
nav_pages:
  - name: Projects
  - name: Publications
# - name: research
# - name: software
# - name: team
# - name: teaching

# Do you want to group your publications by year? {true/false}
group_pub_by_year: true

include:
  - .htaccess
  - _pages

sass:
  sass_dir: _sass

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links
